#!/usr/bin/env bash


exitMSG(){
	echo "Build Failed"
}


gcc -c piemulator.c -pthread -lncurses -o piemulator.o || exitMSG

ar rcs libpie.a piemulator.o || exitMSG

sudo cp libpie.a /usr/local/lib/ || exitMSG

rm piemulator.o

echo "Finished building lpie"
